version: '3'
services:
  web1:
    image: "nginx:latest"
    ports:
      - "10080:80"
    expose:
      - "8080"
    volumes:
      - ./nginx/web1.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/web1.html:/var/www/html/index.html:ro
    depends_on:
      - dns
    networks:
      ournetwork:
        ipv4_address: 172.16.0.10

  web2:
    image: "nginx:latest"
    ports:
      - "10081:80"
    expose:
      - "8080"

    volumes:
      - ./nginx/web2.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/web2.html:/var/www/html/index.html:ro

    depends_on:
      - dns
    networks:
      ournetwork:
        ipv4_address: 172.16.0.11

  db:
    image: "mysql:5.7"
    ports:
      - "13306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "pdns"
      MYSQL_PASSWORD: "pdnspass"
      MYSQL_DATABASE: "pdns"
    networks:
      ournetwork:

  dns:
    build: "powerdns"
    ports:
      - "53/tcp"
      - "53/udp"
    depends_on:
      - db
    networks:
      - ournetwork

networks:
  ournetwork:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/16

